<?php

namespace Database\Seeders;

use App\Models\Medicine;
use App\Models\Category;
use App\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Medicine::truncate();
        Schema::enableForeignKeyConstraints();

        $categories = Category::pluck('id', 'name')->toArray();
        $suppliers = Supplier::pluck('id', 'name')->toArray();

        $medicines = [
            [
                'name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'batch_number' => 'BATCH-001-2026',
                'barcode' => '1234567890123',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'quantity' => 100,
                'unit_price' => 5.00,
                'purchase_price' => 3.00,
                'selling_price' => 6.00,
                'reorder_level' => 20,
                'expiry_date' => '2027-12-31',
                'status' => 'active',
                'shelf_location' => 'A-1-S1',
                'description' => 'Antibiotic for bacterial infections',
                'manufacturer' => 'ABC Pharma',
                'image' => 'images/medicines/amoxicillin.svg',
            ],
            [
                'name' => 'Paracetamol',
                'generic_name' => 'Paracetamol',
                'batch_number' => 'BATCH-002-2026',
                'barcode' => '1234567890124',
                'category_id' => $categories['Pain Relief'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'quantity' => 200,
                'unit_price' => 2.50,
                'purchase_price' => 1.20,
                'selling_price' => 3.00,
                'reorder_level' => 50,
                'expiry_date' => '2028-06-30',
                'status' => 'active',
                'shelf_location' => 'B-2-S2',
                'description' => 'Pain reliever and fever reducer',
                'manufacturer' => 'XYZ Pharma',
                'image' => 'images/medicines/paracetamol.svg',
            ],
            [
                'name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'batch_number' => 'BATCH-003-2026',
                'barcode' => '1234567890125',
                'category_id' => $categories['Pain Relief'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'quantity' => 150,
                'unit_price' => 3.00,
                'purchase_price' => 1.80,
                'selling_price' => 4.00,
                'reorder_level' => 30,
                'expiry_date' => '2027-09-15',
                'status' => 'active',
                'shelf_location' => 'B-2-S3',
                'description' => 'Anti-inflammatory pain reliever',
                'manufacturer' => 'ABC Pharma',
                'image' => 'images/medicines/ibuprofen.svg',
            ],
            [
                'name' => 'Cetirizine',
                'generic_name' => 'Cetirizine',
                'batch_number' => 'BATCH-004-2026',
                'barcode' => '1234567890126',
                'category_id' => $categories['Antihistamines'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'quantity' => 80,
                'unit_price' => 4.00,
                'purchase_price' => 2.50,
                'selling_price' => 5.00,
                'reorder_level' => 15,
                'expiry_date' => '2027-11-30',
                'status' => 'active',
                'shelf_location' => 'G-7-S1',
                'description' => 'Antihistamine for allergy relief',
                'manufacturer' => 'XYZ Pharma',
                'image' => 'images/medicines/cetirizine.svg',
            ],
            [
                'name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'batch_number' => 'BATCH-005-2026',
                'barcode' => '1234567890127',
                'category_id' => $categories['Antacids'] ?? null,
                'supplier_id' => $suppliers['Global Pharma Solutions'] ?? null,
                'quantity' => 60,
                'unit_price' => 6.00,
                'purchase_price' => 3.50,
                'selling_price' => 7.50,
                'reorder_level' => 10,
                'expiry_date' => '2027-10-20',
                'status' => 'active',
                'shelf_location' => 'H-8-S2',
                'description' => 'Proton pump inhibitor for acid reflux',
                'manufacturer' => 'ABC Pharma',
                'image' => 'images/medicines/omeprazole.svg',
            ],
            [
                'name' => 'Metformin 500mg',
                'generic_name' => 'Metformin Hydrochloride',
                'batch_number' => 'BATCH-006-2026',
                'barcode' => '1234567890128',
                'category_id' => $categories['Diabetes Care'] ?? $categories['Vitamins'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'quantity' => 180,
                'unit_price' => 4.50,
                'purchase_price' => 2.20,
                'selling_price' => 5.50,
                'reorder_level' => 35,
                'expiry_date' => '2028-04-15',
                'status' => 'active',
                'shelf_location' => 'C-3-S1',
                'description' => 'First-line medication for type 2 diabetes',
                'manufacturer' => 'Global Meds',
                'image' => 'images/medicines/metformin-500mg.svg',
            ],
            [
                'name' => 'Azithromycin 250mg',
                'generic_name' => 'Azithromycin',
                'batch_number' => 'BATCH-007-2026',
                'barcode' => '1234567890129',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'quantity' => 95,
                'unit_price' => 8.00,
                'purchase_price' => 5.00,
                'selling_price' => 10.50,
                'reorder_level' => 20,
                'expiry_date' => '2027-08-30',
                'status' => 'active',
                'shelf_location' => 'A-1-S2',
                'description' => 'Macrolide antibiotic for respiratory infections',
                'manufacturer' => 'PharmaCorp International',
                'image' => 'images/medicines/azithromycin-250mg.svg',
            ],
            [
                'name' => 'Ciprofloxacin 500mg',
                'generic_name' => 'Ciprofloxacin',
                'batch_number' => 'BATCH-008-2026',
                'barcode' => '1234567890130',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'quantity' => 110,
                'unit_price' => 7.20,
                'purchase_price' => 4.10,
                'selling_price' => 9.00,
                'reorder_level' => 25,
                'expiry_date' => '2027-06-25',
                'status' => 'active',
                'shelf_location' => 'A-1-S3',
                'description' => 'Fluoroquinolone antibiotic',
                'manufacturer' => 'ABC Pharma',
                'image' => 'images/medicines/ciprofloxacin-500mg.svg',
            ],
            [
                'name' => 'Losartan Potassium 50mg',
                'generic_name' => 'Losartan Potassium',
                'batch_number' => 'BATCH-009-2026',
                'barcode' => '1234567890131',
                'category_id' => $categories['Cardiovascular'] ?? null,
                'supplier_id' => $suppliers['Global Pharma Solutions'] ?? null,
                'quantity' => 140,
                'unit_price' => 6.50,
                'purchase_price' => 3.80,
                'selling_price' => 8.20,
                'reorder_level' => 30,
                'expiry_date' => '2028-02-10',
                'status' => 'active',
                'shelf_location' => 'D-4-S1',
                'description' => 'Angiotensin II receptor antagonist for hypertension',
                'manufacturer' => 'CardioHealth PLC',
                'image' => 'images/medicines/losartan-potassium-50mg.svg',
            ],
            [
                'name' => 'Atorvastatin 20mg',
                'generic_name' => 'Atorvastatin Calcium',
                'batch_number' => 'BATCH-010-2026',
                'barcode' => '1234567890132',
                'category_id' => $categories['Cardiovascular'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'quantity' => 125,
                'unit_price' => 9.00,
                'purchase_price' => 5.50,
                'selling_price' => 12.00,
                'reorder_level' => 20,
                'expiry_date' => '2028-01-20',
                'status' => 'active',
                'shelf_location' => 'D-4-S2',
                'description' => 'Statin medication to prevent cardiovascular disease',
                'manufacturer' => 'CardioHealth PLC',
                'image' => 'images/medicines/atorvastatin-20mg.svg',
            ],
            [
                'name' => 'Salbutamol Inhaler 100mcg',
                'generic_name' => 'Salbutamol / Albuterol',
                'batch_number' => 'BATCH-011-2026',
                'barcode' => '1234567890133',
                'category_id' => $categories['Respiratory'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'quantity' => 75,
                'unit_price' => 11.00,
                'purchase_price' => 7.00,
                'selling_price' => 14.50,
                'reorder_level' => 15,
                'expiry_date' => '2027-11-15',
                'status' => 'active',
                'shelf_location' => 'E-5-S1',
                'description' => 'Fast-acting bronchodilator for asthma relief',
                'manufacturer' => 'PulmoCare Ltd',
                'image' => 'images/medicines/salbutamol-inhaler-100mcg.svg',
            ],
            [
                'name' => 'Augmentin 625mg',
                'generic_name' => 'Amoxicillin + Clavulanic Acid',
                'batch_number' => 'BATCH-012-2026',
                'barcode' => '1234567890134',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['Global Pharma Solutions'] ?? null,
                'quantity' => 85,
                'unit_price' => 12.50,
                'purchase_price' => 8.00,
                'selling_price' => 16.00,
                'reorder_level' => 20,
                'expiry_date' => '2027-07-31',
                'status' => 'active',
                'shelf_location' => 'A-1-S4',
                'description' => 'Broad-spectrum antibiotic combination',
                'manufacturer' => 'GSK Health',
                'image' => 'images/medicines/augmentin-625mg.svg',
            ],
            [
                'name' => 'Hydrochlorothiazide 25mg',
                'generic_name' => 'Hydrochlorothiazide',
                'batch_number' => 'BATCH-013-2026',
                'barcode' => '1234567890135',
                'category_id' => $categories['Cardiovascular'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'quantity' => 160,
                'unit_price' => 3.50,
                'purchase_price' => 1.80,
                'selling_price' => 4.50,
                'reorder_level' => 30,
                'expiry_date' => '2028-05-20',
                'status' => 'active',
                'shelf_location' => 'D-4-S3',
                'description' => 'Thiazide diuretic for blood pressure control',
                'manufacturer' => 'XYZ Pharma',
                'image' => 'images/medicines/hydrochlorothiazide-25mg.svg',
            ],
            [
                'name' => 'Metoprolol Tartrate 50mg',
                'generic_name' => 'Metoprolol Tartrate',
                'batch_number' => 'BATCH-014-2026',
                'barcode' => '1234567890136',
                'category_id' => $categories['Cardiovascular'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'quantity' => 105,
                'unit_price' => 5.20,
                'purchase_price' => 3.00,
                'selling_price' => 7.00,
                'reorder_level' => 20,
                'expiry_date' => '2027-12-10',
                'status' => 'active',
                'shelf_location' => 'D-4-S4',
                'description' => 'Beta-blocker for hypertension and angina',
                'manufacturer' => 'CardioHealth PLC',
                'image' => 'images/medicines/metoprolol-tartrate-50mg.svg',
            ],
            [
                'name' => 'Doxycycline 100mg',
                'generic_name' => 'Doxycycline Hyclate',
                'batch_number' => 'BATCH-015-2026',
                'barcode' => '1234567890137',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['Global Pharma Solutions'] ?? null,
                'quantity' => 90,
                'unit_price' => 6.80,
                'purchase_price' => 3.90,
                'selling_price' => 8.80,
                'reorder_level' => 18,
                'expiry_date' => '2027-09-05',
                'status' => 'active',
                'shelf_location' => 'A-1-S5',
                'description' => 'Tetracycline antibiotic for bacterial infections',
                'manufacturer' => 'ABC Pharma',
                'image' => 'images/medicines/doxycycline-100mg.svg',
            ],
        ];

        foreach ($medicines as $med) {
            Medicine::create($med);
        }

        $this->command->info('✅ Medicines created: ' . count($medicines));
    }
}