<?php

namespace Database\Seeders;

use App\Models\Medicine;
use App\Models\Category;
use App\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Medicine::truncate();
        Schema::enableForeignKeyConstraints();

        $categories = Category::pluck('id', 'name')->toArray();
        $suppliers  = Supplier::pluck('id', 'name')->toArray();

        $medicines = [
            [
                'name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'batch_number' => 'BATCH-001-2026',
                'barcode' => '1234567890123',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'prescription' => true,
                'dosage_form' => 'capsule',
                'strength' => '500 mg',
                'unit' => 'box',
                'shelf_location' => 'A-1-S1',
                'manufacturer' => 'ABC Pharma',
                'image' => null,
            ],
            [
                'name' => 'Paracetamol',
                'generic_name' => 'Paracetamol',
                'batch_number' => 'BATCH-002-2026',
                'barcode' => '1234567890124',
                'category_id' => $categories['Pain Relief'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'prescription' => false,
                'dosage_form' => 'tablet',
                'strength' => '500 mg',
                'unit' => 'box',
                'shelf_location' => 'B-2-S2',
                'manufacturer' => 'XYZ Pharma',
                'image' => null,
            ],
            [
                'name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'batch_number' => 'BATCH-003-2026',
                'barcode' => '1234567890125',
                'category_id' => $categories['Pain Relief'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'prescription' => false,
                'dosage_form' => 'tablet',
                'strength' => '400 mg',
                'unit' => 'box',
                'shelf_location' => 'B-2-S3',
                'manufacturer' => 'ABC Pharma',
                'image' => null,
            ],
            [
                'name' => 'Cetirizine',
                'generic_name' => 'Cetirizine',
                'batch_number' => 'BATCH-004-2026',
                'barcode' => '1234567890126',
                'category_id' => $categories['Antihistamines'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'prescription' => false,
                'dosage_form' => 'tablet',
                'strength' => '10 mg',
                'unit' => 'box',
                'shelf_location' => 'G-7-S1',
                'manufacturer' => 'XYZ Pharma',
                'image' => null,
            ],
            [
                'name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'batch_number' => 'BATCH-005-2026',
                'barcode' => '1234567890127',
                'category_id' => $categories['Antacids'] ?? null,
                'supplier_id' => $suppliers['Global Pharma Solutions'] ?? null,
                'prescription' => false,
                'dosage_form' => 'capsule',
                'strength' => '20 mg',
                'unit' => 'box',
                'shelf_location' => 'H-8-S2',
                'manufacturer' => 'ABC Pharma',
                'image' => null,
            ],
            [
                'name' => 'Metformin 500mg',
                'generic_name' => 'Metformin Hydrochloride',
                'batch_number' => 'BATCH-006-2026',
                'barcode' => '1234567890128',
                'category_id' => $categories['Diabetes'] ?? $categories['Vitamins'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'prescription' => true,
                'dosage_form' => 'tablet',
                'strength' => '500 mg',
                'unit' => 'box',
                'shelf_location' => 'C-3-S1',
                'manufacturer' => 'Global Meds',
                'image' => null,
            ],
            [
                'name' => 'Azithromycin 250mg',
                'generic_name' => 'Azithromycin',
                'batch_number' => 'BATCH-007-2026',
                'barcode' => '1234567890129',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'prescription' => true,
                'dosage_form' => 'tablet',
                'strength' => '250 mg',
                'unit' => 'box',
                'shelf_location' => 'A-1-S2',
                'manufacturer' => 'PharmaCorp International',
                'image' => null,
            ],
            [
                'name' => 'Ciprofloxacin 500mg',
                'generic_name' => 'Ciprofloxacin',
                'batch_number' => 'BATCH-008-2026',
                'barcode' => '1234567890130',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'prescription' => true,
                'dosage_form' => 'tablet',
                'strength' => '500 mg',
                'unit' => 'box',
                'shelf_location' => 'A-1-S3',
                'manufacturer' => 'ABC Pharma',
                'image' => null,
            ],
            [
                'name' => 'Losartan Potassium 50mg',
                'generic_name' => 'Losartan Potassium',
                'batch_number' => 'BATCH-009-2026',
                'barcode' => '1234567890131',
                'category_id' => $categories['Cardiovascular'] ?? null,
                'supplier_id' => $suppliers['Global Pharma Solutions'] ?? null,
                'prescription' => true,
                'dosage_form' => 'tablet',
                'strength' => '50 mg',
                'unit' => 'box',
                'shelf_location' => 'D-4-S1',
                'manufacturer' => 'CardioHealth PLC',
                'image' => null,
            ],
            [
                'name' => 'Atorvastatin 20mg',
                'generic_name' => 'Atorvastatin Calcium',
                'batch_number' => 'BATCH-010-2026',
                'barcode' => '1234567890132',
                'category_id' => $categories['Cardiovascular'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'prescription' => true,
                'dosage_form' => 'tablet',
                'strength' => '20 mg',
                'unit' => 'box',
                'shelf_location' => 'D-4-S2',
                'manufacturer' => 'CardioHealth PLC',
                'image' => null,
            ],
            [
                'name' => 'Salbutamol Inhaler 100mcg',
                'generic_name' => 'Salbutamol / Albuterol',
                'batch_number' => 'BATCH-011-2026',
                'barcode' => '1234567890133',
                'category_id' => $categories['Respiratory'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'prescription' => true,
                'dosage_form' => 'injection',
                'strength' => '100 mcg',
                'unit' => 'vial',
                'shelf_location' => 'E-5-S1',
                'manufacturer' => 'PulmoCare Ltd',
                'image' => null,
            ],
            [
                'name' => 'Augmentin 625mg',
                'generic_name' => 'Amoxicillin + Clavulanic Acid',
                'batch_number' => 'BATCH-012-2026',
                'barcode' => '1234567890134',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['Global Pharma Solutions'] ?? null,
                'prescription' => true,
                'dosage_form' => 'tablet',
                'strength' => '625 mg',
                'unit' => 'box',
                'shelf_location' => 'A-1-S4',
                'manufacturer' => 'GSK Health',
                'image' => null,
            ],
            [
                'name' => 'Hydrochlorothiazide 25mg',
                'generic_name' => 'Hydrochlorothiazide',
                'batch_number' => 'BATCH-013-2026',
                'barcode' => '1234567890135',
                'category_id' => $categories['Cardiovascular'] ?? null,
                'supplier_id' => $suppliers['PharmaDistributors PLC'] ?? null,
                'prescription' => true,
                'dosage_form' => 'tablet',
                'strength' => '25 mg',
                'unit' => 'box',
                'shelf_location' => 'D-4-S3',
                'manufacturer' => 'XYZ Pharma',
                'image' => null,
            ],
            [
                'name' => 'Metoprolol Tartrate 50mg',
                'generic_name' => 'Metoprolol Tartrate',
                'batch_number' => 'BATCH-014-2026',
                'barcode' => '1234567890136',
                'category_id' => $categories['Cardiovascular'] ?? null,
                'supplier_id' => $suppliers['MediSupply Ltd'] ?? null,
                'prescription' => true,
                'dosage_form' => 'tablet',
                'strength' => '50 mg',
                'unit' => 'box',
                'shelf_location' => 'D-4-S4',
                'manufacturer' => 'CardioHealth PLC',
                'image' => null,
            ],
            [
                'name' => 'Doxycycline 100mg',
                'generic_name' => 'Doxycycline Hyclate',
                'batch_number' => 'BATCH-015-2026',
                'barcode' => '1234567890137',
                'category_id' => $categories['Antibiotics'] ?? null,
                'supplier_id' => $suppliers['Global Pharma Solutions'] ?? null,
                'prescription' => true,
                'dosage_form' => 'capsule',
                'strength' => '100 mg',
                'unit' => 'box',
                'shelf_location' => 'A-1-S5',
                'manufacturer' => 'ABC Pharma',
                'image' => null,
            ],
        ];

        foreach ($medicines as $med) {
            Medicine::create($med);
        }

        $this->command->info('✅ Medicines created: ' . count($medicines));
    }
}
