<?php
$f = __DIR__ . '/app/Http/Controllers/DashboardController.php';
$c = file_get_contents($f);

// 1. Add purchasing staff dispatch in index()
$old = "        if (\$user->isPharmacist()) {\n            return response()->json(\n                \$this->pharmacistDashboard()\n            );\n        }\n\n        return response()->json(";
$new = "        if (\$user->isPharmacist()) {\n            return response()->json(\n                \$this->pharmacistDashboard()\n            );\n        }\n\n        if (\$user->isPurchasingStaff()) {\n            return response()->json(\n                \$this->purchasingStaffDashboard()\n            );\n        }\n\n        return response()->json(";
$c = str_replace($old, $new, $c);

// 2. Add purchasingStaffDashboard method before closing brace
$m = "\n    /*\n    | Purchasing Staff dashboard - purchasing focus\n    |*/\n    private function purchasingStaffDashboard()\n    {\n        \$today           = today();\n        \$thirtyDaysAgo   = \$today->copy()->subDays(30);\n\n        \$totalSuppliers       = Supplier::count();\n        \$totalPurchaseOrders  = PurchaseOrder::count();\n        \$poStats              = \$this->purchaseOrderStats();\n\n        \$pendingPOs           = PurchaseOrder::where('status', 'pending')->count();\n        \$pendingReceiving     = PurchaseOrder::whereIn('status', ['sent', 'delivered'])->count();\n\n        \$completedThisMonth   = PurchaseOrder::where('status', 'completed')\n            ->whereMonth('created_at', \$today->month)\n            ->whereYear('created_at', \$today->year)\n            ->count();\n\n        \$totalSpendThisMonth  = (float) PurchaseOrder::where('status', 'completed')\n            ->whereMonth('created_at', \$today->month)\n            ->whereYear('created_at', \$today->year)\n            ->sum('total_amount');\n\n        \$recentPurchaseOrders = PurchaseOrder::with('supplier')\n            ->where('created_at', '>=', \$thirtyDaysAgo)\n            ->latest()\n            ->take(10)\n            ->get();\n\n        \$activities           = \$this->recentActivities(5);\n\n        return [\n            'todaySalesCount'        => Sale::whereDate('sale_date', \$today)->count(),\n            'todayRevenue'           => Sale::whereDate('sale_date', \$today)->sum('total_amount'),\n            'totalSuppliers'          => \$totalSuppliers,\n            'totalPurchaseOrders'     => \$totalPurchaseOrders,\n            'pendingPurchaseOrders'   => \$pendingPOs,\n            'pendingReceiving'        => \$pendingReceiving,\n            'completedThisMonth'      => \$completedThisMonth,\n            'totalSpendThisMonth'     => \$totalSpendThisMonth,\n            'recentPurchaseOrders'    => \$recentPurchaseOrders,\n            'recentActivities'        => \$activities,\n            'purchaseOrderStats'      => \$poStats,\n            'totalProducts'           => Medicine::count(),\n        ];\n    }\n";

$c = preg_replace('/\n\}\s*$/', $m . "\n}", $c);
file_put_contents($f, $c);
echo "Done: non-API DashboardController updated.\n";
