// resources/js/context/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const LANGUAGE_KEY = 'language';

const translations = {
  en: {
    "Actions": "Actions",
    "Active": "Active",
    "Add Medicine": "Add Medicine",
    "Add New Medicine": "Add New Medicine",
    "Add User": "Add User",
    "Add items to get started": "Add items to get started",
    "Administration": "Administration",
    "Alerts": "Alerts",
    "All Categories": "All Categories",
    "All Statuses": "All Statuses",
    "Approved": "Approved",
    "Audit Logs": "Audit Logs",
    "Branch": "Branch",
    "Branches": "Branches",
    "Categories & Shelves": "Categories & Shelves",
    "Clear All": "Clear All",
    "Completed": "Completed",
    "Create orders and send to cashier": "Create orders and send to cashier",
    "Created": "Created",
    "Current Order": "Current Order",
    "Customer": "Customer",
    "Dashboard": "Dashboard",
    "Date & Time": "Date & Time",
    "Discontinued": "Discontinued",
    "Email": "Email",
    "Expired": "Expired",
    "Expired Medicines": "Expired Medicines",
    "Expiring Within 90 Days": "Expiring Within 90 Days",
    "Inactive": "Inactive",
    "Inventory & Warehousing": "Inventory & Warehousing",
    "Inventory Status": "Inventory Status",
    "Low Stock Medicines": "Low Stock Medicines",
    "Main": "Main",
    "Medicines": "Medicines",
    "Name": "Name",
    "No recent sales.": "No recent sales.",
    "No sales recorded for today yet.": "No sales recorded for today yet.",
    "Order is empty": "Order is empty",
    "Pending": "Pending",
    "Pending Cashier": "Pending Cashier",
    "Point of Sale": "Point of Sale",
    "Product Management": "Product Management",
    "Purchase Orders": "Purchase Orders",
    "Quick Actions": "Quick Actions",
    "Receipt": "Receipt",
    "Recent Activity": "Recent Activity",
    "Recent Sales": "Recent Sales",
    "Rejected": "Rejected",
    "Reports": "Reports",
    "Reports & Analytics": "Reports & Analytics",
    "Retail & OTC": "Retail & OTC",
    "Retail & OTC Products": "Retail & OTC Products",
    "Role": "Role",
    "Roles & Permissions": "Roles & Permissions",
    "Sales": "Sales",
    "Sales Analytics": "Sales Analytics",
    "Sales Checkout": "Sales Checkout",
    "Sales History": "Sales History",
    "Status": "Status",
    "Stock Management": "Stock Management",
    "Stock Movements": "Stock Movements",
    "Suppliers": "Suppliers",
    "Today": "Today",
    "Today's Revenue": "Today's Revenue",
    "Today's Sales": "Today's Sales",
    "Today's Sales by Hour": "Today's Sales by Hour",
    "Total": "Total",
    "Total Medicines": "Total Medicines",
    "User Management": "User Management",
    "Users": "Users",
    "View All": "View All",
    "Warehouse": "Warehouse"
  },
  am: {
    "% Used": "% ጥቅም ላይ የዋለ",
    "% of total": "ከአጠቃላይ %",
    "(Capacity:": "(አቅም:",
    "(Stock:": "(ክምችት:",
    ".\n                        Choose a": "። ይምረጡ",
    "/ Reorder:": "/ ድጋሚ ማዘዣ:",
    "/ unit": "/ በክፍል",
    "1. Add Products": "1. ምርቶችን ጨምር",
    "1. Supplier *": "1. አቅራቢ *",
    "2. Add Products": "2. ምርቶችን ጨምር",
    "2. Movement Type": "2. የእንቅስቃሴ አይነት",
    "3. Details & Confirm": "3. ዝርዝሮች እና ማረጋገጫ",
    "3. Selected Items (": "3. የተመረጡ እቃዎች (",
    "ADMIN": "አስተዳዳሪ",
    "Account Settings": "የመለያ ቅንብሮች",
    "Action": "እርምጃ",
    "Actions": "እርምጃዎች",
    "Active": "ንቁ",
    "Active Branch:": "ንቁ ቅርንጫፍ:",
    "Active Users": "ንቁ ተጠቃሚዎች",
    "Add": "ጨምር",
    "Add +": "ጨምር +",
    "Add Branch": "ቅርንጫፍ ጨምር",
    "Add Category": "ምድብ ጨምር",
    "Add Medicine": "መድኃኒት ጨምር",
    "Add New Category": "አዲስ ምድብ ጨምር",
    "Add New Medicine": "አዲስ መድኃኒት ጨምር",
    "Add New Retail Product": "አዲስ የችርቻሮ ምርት ጨምር",
    "Add New Supplier": "አዲስ አቅራቢ ጨምር",
    "Add User": "ተጠቃሚ ጨምር",
    "Add at least one item to the order": "ቢያንስ አንድ እቃ ወደ ትዕዛዙ ይጨምሩ",
    "Add items to get started": "ለመጀመር እቃዎችን ይጨምሩ",
    "Add multiple items and record a single movement type": "በርካታ እቃዎችን ይጨምሩ እና አንድ የእንቅስቃሴ አይነት ይመዝግቡ",
    "Add to Order": "ወደ ትዕዛዝ ጨምር",
    "Added": "ተጨምሯል",
    "Additional details about this medicine": "ስለዚህ መድኃኒት ተጨማሪ ዝርዝሮች",
    "Additional details about this product": "ስለዚህ ምርት ተጨማሪ ዝርዝሮች",
    "Address": "አድራሻ",
    "Adjustments": "ማስተካከያዎች",
    "Admin": "አስተዳዳሪ",
    "Admin Portal": "የአስተዳዳሪ ፖርታል",
    "Admin User": "አስተዳዳሪ ተጠቃሚ",
    "Administration": "አስተዳደር",
    "Admins": "አስተዳዳሪዎች",
    "Admins automatically have every permission in the system.": "አስተዳዳሪዎች በስርዓቱ ውስጥ ያሉትን ሁሉንም ፈቃዶች በራስ-ሰር ያገኛሉ።",
    "After": "በኋላ",
    "After Stock": "ከክምችት በኋላ",
    "After Values": "የበኋላ እሴቶች",
    "Alerts": "ማሳሰቢያዎች",
    "All Actions": "ሁሉም እርምጃዎች",
    "All Branches": "ሁሉም ቅርንጫፎች",
    "All Branches (Global)": "ሁሉም ቅርንጫፎች (አጠቃላይ)",
    "All Cashiers": "ሁሉም ገንዘብ ተቀባዮች",
    "All Categories": "ሁሉም ምድቦች",
    "All Medicines": "ሁሉም መድኃኒቶች",
    "All Medicines (": "ሁሉም መድኃኒቶች (",
    "All Modules": "ሁሉም ሞጁሎች",
    "All Payment Methods": "ሁሉም የክፍያ ዘዴዎች",
    "All Products": "ሁሉም ምርቶች",
    "All Products (": "ሁሉም ምርቶች (",
    "All Purchase Orders (": "ሁሉም የግዢ ትዕዛዞች (",
    "All Retail Products (": "ሁሉም የችርቻሮ ምርቶች (",
    "All Roles": "ሁሉም ሚናዎች",
    "All Status": "ሁሉም ሁኔታ",
    "All Statuses": "ሁሉም ሁኔታዎች",
    "All Stocked Up!": "ሁሉም ተከማችቷል!",
    "All Suppliers": "ሁሉም አቅራቢዎች",
    "All Suppliers (": "ሁሉም አቅራቢዎች (",
    "All Types": "ሁሉም አይነቶች",
    "All Users": "ሁሉም ተጠቃሚዎች",
    "All items must have quantity > 0": "ሁሉም እቃዎች ብዛት ከ 0 በላይ መሆን አለበት",
    "All medicines in inventory": "በክምችት ውስጥ ያሉ ሁሉም መድኃኒቶች",
    "All products are well-stocked!": "ሁሉም ምርቶች በደንብ ተከማችተዋል!",
    "Already have an account?": "ቀደም ሲል አካውንት አለዎት?",
    "Amount": "መጠን",
    "Amount Paid": "የተከፈለ መጠን",
    "Amount Paid:": "የተከፈለ መጠን:",
    "Amount paid cannot be less than the total amount": "የተከፈለው መጠን ከአጠቃላይ መጠን ያነሰ ሊሆን አይችልም",
    "Apply Discount": "ቅናሽ አድርግ",
    "Apply Filters": "ማጣሪያዎችን ተግብር",
    "Approve": "አጽድቅ",
    "Approve this transfer request?": "ይህንን የዝውውር ጥያቄ ያጸድቃሉ?",
    "Approved": "የጸደቀ",
    "Assigned Branch": "የተመደበ ቅርንጫፍ",
    "Audit Log Details": "የኦዲት መዝገብ ዝርዝሮች",
    "Audit Logs": "የኦዲት መዝገቦች",
    "Audit logs exported successfully": "የኦዲት መዝገቦች በተሳካ ሁኔታ ተልከዋል",
    "Available · Status:": "የሚገኝ · ሁኔታ:",
    "Back": "ተመለስ",
    "Back to Categories": "ወደ ምድቦች ተመለስ",
    "Back to Home": "ወደ ዋና ገጽ ተመለስ",
    "Back to Login": "ወደ መግቢያ ገጽ ተመለስ",
    "Back to Purchase Orders": "ወደ ግዢ ትዕዛዞች ተመለስ",
    "Back to Suppliers": "ወደ አቅራቢዎች ተመለስ",
    "Barcode": "ባርኮድ",
    "Barcode scanning is not supported in this browser.": "የባርኮድ ቅኝት በዚህ ብሮውዘር ላይ አይሰራም።",
    "Barcode:": "ባርኮድ:",
    "Batch": "ባች",
    "Batch / SKU": "ባች / ኤስኬዩ",
    "Batch Number": "የባች ቁጥር",
    "Batch Number *": "የባች ቁጥር *",
    "Batch:": "ባች:",
    "Before": "በፊት",
    "Before Stock": "ከክምችት በፊት",
    "Before Values": "የበፊት እሴቶች",
    "Branch": "ቅርንጫፍ",
    "Branch *": "ቅርንጫፍ *",
    "Branch Details": "የቅርንጫፍ ዝርዝሮች",
    "Branch Management": "የቅርንጫፍ አስተዳደር",
    "Branch Name *": "የቅርንጫፍ ስም *",
    "Branch Scoped View:": "የቅርንጫፍ እይታ:",
    "Branch created successfully": "ቅርንጫፍ በተሳካ ሁኔታ ተፈጥሯል",
    "Branch deleted successfully": "ቅርንጫፍ በተሳካ ሁኔታ ተሰርዟል",
    "Branch updated successfully": "ቅርንጫፍ በተሳካ ሁኔታ ተሻሽሏል",
    "Branch:": "ቅርንጫፍ:",
    "Branches": "ቅርንጫፎች",
    "Browse OTC products and send to cashier queue": "ያለ ማዘዣ የሚሸጡ ምርቶችን ይፈልጉ እና ለገንዘብ ተቀባይ ይላኩ",
    "By:": "በ:",
    "CSV": "ሲኤስቪ",
    "Cancel": "ሰርዝ",
    "Cancel scan": "ቅኝትን ሰርዝ",
    "Capacity": "አቅም",
    "Capacity *": "አቅም *",
    "Capacity Load": "የአቅም ጭነት",
    "Capacity:": "አቅም:",
    "Card Grid View (Warehouse Style)": "የካርድ ፍርግርግ እይታ (የመጋዘን ዘይቤ)",
    "Cards": "ካርዶች",
    "Cart is empty": "ጋሪው ባዶ ነው",
    "Cashier": "ገንዘብ ተቀባይ",
    "Cashier will collect payment and print receipt": "ገንዘብ ተቀባይ ክፍያ ይሰበስባል እና ደረሰኝ ያትማል",
    "Cashiers": "ገንዘብ ተቀባዮች",
    "Categories": "ምድቦች",
    "Categories & Shelves": "ምድቦች እና መደርደሪያዎች",
    "Category": "ምድብ",
    "Category *": "ምድብ *",
    "Category Details": "የምድብ ዝርዝሮች",
    "Category Name": "የምድብ ስም",
    "Category Name *": "የምድብ ስም *",
    "Category created successfully": "ምድብ በተሳካ ሁኔታ ተፈጥሯል",
    "Category deleted successfully": "ምድብ በተሳካ ሁኔታ ተሰርዟል",
    "Category not found.": "ምድብ አልተገኘም።",
    "Category updated successfully": "ምድብ በተሳካ ሁኔታ ተሻሽሏል",
    "Category:": "ምድብ:",
    "Central Warehouse": "ማዕከላዊ መጋዘን",
    "Central Warehouse Shelves": "የማዕከላዊ መጋዘን መደርደሪያዎች",
    "Change": "ለውጥ",
    "Change Password": "የይለፍ ቃል ቀይር",
    "Change to return:": "የሚመለስ መልስ:",
    "Change:": "ለውጥ:",
    "Checking permissions...": "ፈቃዶች በመፈተሽ ላይ...",
    "Choose Image": "ምስል ይምረጡ",
    "Clear": "አጽዳ",
    "Clear All": "ሁሉንም አጽዳ",
    "Clear filters": "ማጣሪያዎችን አጽዳ",
    "Click \"Add Medicine\" or \"Retail & OTC\"": "\"መድኃኒት ጨምር\" ወይም \"ችርቻሮ እና ኦቲሲ\" የሚለውን ይጫኑ",
    "Click to upload photo": "ፎቶ ለመጫን እዚህ ይጫኑ",
    "Click to view full breakout...": "ሙሉ መግለጫውን ለማየት እዚህ ይጫኑ...",
    "Close": "ዝጋ",
    "Complete": "ተጠናቋል",
    "Complete Order": "ትዕዛዝ አጠናቅቅ",
    "Complete Sale": "ሽያጭ አጠናቅቅ",
    "Complete Transfer": "ዝውውር አጠናቅቅ",
    "Complete Transfer — Select Destination Shelf": "ዝውውር አጠናቅቅ — መድረሻ መደርደሪያ ይምረጡ",
    "Complete audit trail of all system activities": "የሁሉም የስርዓት እንቅስቃሴዎች ሙሉ የኦዲት መዝገብ",
    "Completed": "ተጠናቋል",
    "Confirm New Password": "አዲስ የይለፍ ቃል አረጋግጥ",
    "Confirm Password": "የይለፍ ቃል አረጋግጥ",
    "Confirm Payment": "ክፍያ አረጋግጥ",
    "Confirm Receiving": "መቀበልን አረጋግጥ",
    "Confirm Restock": "ድጋሚ መሙላትን አረጋግጥ",
    "Confirm new password": "አዲስ የይለፍ ቃል አረጋግጥ",
    "Confirm password": "የይለፍ ቃል አረጋግጥ",
    "Contact": "ዕውቂያ",
    "Contact Person": "የዕውቂያ ሰው",
    "Continue": "ቀጥል",
    "Controlled Substance": "ቁጥጥር የሚደረግበት ንጥረ ነገር",
    "Create Account": "አካውንት ይፍጠሩ",
    "Create Category": "ምድብ ፍጠር",
    "Create Order": "ትዕዛዝ ፍጠር",
    "Create Prescription Sale": "የማዘዣ ሽያጭ ፍጠር",
    "Create Purchase Order": "የግዢ ትዕዛዝ ፍጠር",
    "Create Retail Sale": "የችርቻሮ ሽያጭ ፍጠር",
    "Create Supplier": "አቅራቢ ፍጠር",
    "Create Transfer Request": "የዝውውር ጥያቄ ፍጠር",
    "Create one": "አንድ ፍጠር",
    "Create orders and send to cashier": "ትዕዛዞችን ይፍጠሩ እና ለገንዘብ ተቀባይ ይላኩ",
    "Created": "የተፈጠረበት",
    "Creating Account...": "አካውንት በመፍጠር ላይ...",
    "Critical": "አስቸኳይ",
    "Current Order": "የአሁኑ ትዕዛዝ",
    "Current Password": "የአሁኑ የይለፍ ቃል",
    "Current Stock": "የአሁኑ ክምችት",
    "Customer": "ደንበኛ",
    "Customer Details": "የደንበኛ ዝርዝሮች",
    "Customer Email": "የደንበኛ ኢሜይል",
    "Customer Information": "የደንበኛ መረጃ",
    "Customer Name": "የደንበኛ ስም",
    "Customer Phone": "የደንበኛ ስልክ",
    "Customer Phone Number": "የደንበኛ ስልክ ቁጥር",
    "Customer name": "የደንበኛ ስም",
    "Customer phone number is required": "የደንበኛ ስልክ ቁጥር ያስፈልጋል",
    "Daily": "ዕለታዊ",
    "Daily, weekly, and monthly sales trends": "ዕለታዊ፣ ሳምንታዊ እና ወርሃዊ የሽያጭ አዝማሚያዎች",
    "Damaged": "የተበላሸ",
    "Dashboard": "ዳሽቦርድ",
    "Date": "ቀን",
    "Date & Time": "ቀን እና ሰዓት",
    "Date From": "ከቀን",
    "Date To": "እስከ ቀን",
    "Date of Birth": "የትውልድ ቀን",
    "Days Left": "Days Left",
    "Decrease quantity": "Decrease quantity",
    "Degree": "Degree",
    "Degree Certificate": "Degree Certificate",
    "Delete": "Delete",
    "Delete Medicine": "Delete Medicine",
    "Delete Shelf": "መደርደሪያ ሰርዝ",
    "Delete role": "Delete role",
    "Delete this branch? This action cannot be undone.": "branch? This action cannot be undone. ይሰርዙ?",
    "Delete this category? This will not delete associated medicines.": "category? This will not delete associated medicines. ይሰርዙ?",
    "Delete this purchase order?": "purchase order? ይሰርዙ?",
    "Delete this shelf? This will not delete associated medicines.": "shelf? This will not delete associated medicines. ይሰርዙ?",
    "Delete this supplier?": "ይህንን አቅራቢ መሰረዝ ይፈልጋሉ?",
    "Delivered At": "Delivered At",
    "Description": "መግለጫ",
    "Destination": "Destination",
    "Destination Branch *": "Destination Branch *",
    "Destination Shelf *": "Destination Shelf *",
    "Destination Type": "Destination Type",
    "Details": "ዝርዝሮች",
    "Discontinued": "የተቋረጠ",
    "Discount": "ቅናሽ",
    "Discount (": "Discount (",
    "Dispense medications and send to cashier queue": "Dispense medications and send to cashier queue",
    "Don't have an account?": "አካውንት የለዎትም?",
    "Dosage": "Dosage",
    "Dosage Form": "Dosage Form",
    "Download PDF": "ፒዲኤፍ አውርድ",
    "Download PDF Receipt": "Download PDF Receipt",
    "Duplicate": "Duplicate",
    "EN": "እንግሊዝኛ",
    "Edit": "አስተካክል",
    "Edit Branch": "Edit Branch",
    "Edit Category": "ምድብ አስተካክል",
    "Edit Medicine": "መድኃኒት አስተካክል",
    "Edit Product": "ምርት አስተካክል",
    "Edit Profile": "Edit Profile",
    "Edit Purchase Order": "Edit Purchase Order",
    "Edit Shelf": "Edit Shelf",
    "Edit Supplier": "አቅራቢ አስተካክል",
    "Email": "ኢሜይል",
    "Email Address": "የኢሜይል አድራሻ",
    "Email address": "Email address",
    "Enter a valid quantity": "Enter a valid quantity",
    "Enter customer name": "Enter customer name",
    "Enter customer phone number": "Enter customer phone number",
    "Enter email address": "Enter email address",
    "Enter first name": "Enter first name",
    "Enter full address": "Enter full address",
    "Enter last name": "Enter last name",
    "Enter license number": "Enter license number",
    "Enter national ID": "Enter national ID",
    "Enter new password": "አዲስ የይለፍ ቃል ያስገቡ",
    "Enter or scan barcode": "Enter or scan barcode",
    "Enter patient name": "Enter patient name",
    "Enter phone number": "Enter phone number",
    "Enter qualification": "Enter qualification",
    "Enter quantity": "Enter quantity",
    "Enter this code on the customer's Telebirr app to complete the payment.": "Enter this code on the customer's Telebirr app to complete the payment.",
    "Enter your password": "Enter your password",
    "EthioPharmacy": "ኢትዮ ፋርማሲ",
    "Expected Delivery": "Expected Delivery",
    "Expired": "ጊዜው ያለፈበት",
    "Expired Medicines": "ጊዜያቸው ያለፈባቸው መድኃኒቶች",
    "Expired:": "Expired:",
    "Expires:": "Expires:",
    "Expiring Soon": "Expiring Soon",
    "Expiring Soon (90 days)": "Expiring Soon (90 days)",
    "Expiring Within 90 Days": "በ90 ቀናት ውስጥ የሚያልፉ",
    "Expiry": "Expiry",
    "Expiry Date": "የሚያበቃበት ቀን",
    "Expiry Date *": "የሚያበቃበት ቀን *",
    "Expiry Management": "Expiry Management",
    "Expiry Report — Expiring Soon (90 days) (": "Expiry Report — Expiring Soon (90 days) (",
    "Export": "Export",
    "Export CSV": "Export CSV",
    "Export PDF": "Export PDF",
    "Export Report": "Export Report",
    "Failed to approve transfer": "አልተሳካም -  approve transfer",
    "Failed to approve user. Please try again.": "አልተሳካም -  approve user. Please try again.",
    "Failed to delete branch": "አልተሳካም -  delete branch",
    "Failed to delete category": "አልተሳካም -  delete category",
    "Failed to delete medicine": "አልተሳካም -  delete medicine",
    "Failed to delete retail product": "አልተሳካም -  delete retail product",
    "Failed to delete supplier": "አልተሳካም -  delete supplier",
    "Failed to delete user": "አልተሳካም -  delete user",
    "Failed to download receipt PDF": "አልተሳካም -  download receipt PDF",
    "Failed to export audit logs": "አልተሳካም -  export audit logs",
    "Failed to export sales report": "አልተሳካም -  export sales report",
    "Failed to fetch cashier queue": "አልተሳካም -  fetch cashier queue",
    "Failed to load audit logs": "አልተሳካም -  load audit logs",
    "Failed to load branches": "አልተሳካም -  load branches",
    "Failed to load categories": "አልተሳካም -  load categories",
    "Failed to load category": "አልተሳካም -  load category",
    "Failed to load dashboard data": "አልተሳካም -  load dashboard data",
    "Failed to load low stock data": "አልተሳካም -  load low stock data",
    "Failed to load medicines": "አልተሳካም -  load medicines",
    "Failed to load medicines on this shelf": "አልተሳካም -  load medicines on this shelf",
    "Failed to load products": "አልተሳካም -  load products",
    "Failed to load purchase orders": "አልተሳካም -  load purchase orders",
    "Failed to load receipt": "አልተሳካም -  load receipt",
    "Failed to load retail products": "አልተሳካም -  load retail products",
    "Failed to load roles & permissions": "አልተሳካም -  load roles & permissions",
    "Failed to load sale details": "አልተሳካም -  load sale details",
    "Failed to load sales history": "አልተሳካም -  load sales history",
    "Failed to load shelf items": "አልተሳካም -  load shelf items",
    "Failed to load shelves": "አልተሳካም -  load shelves",
    "Failed to load stock data": "አልተሳካም -  load stock data",
    "Failed to load stock movements": "አልተሳካም -  load stock movements",
    "Failed to load supplier": "አልተሳካም -  load supplier",
    "Failed to load users": "አልተሳካም -  load users",
    "Failed to load warehouse data": "አልተሳካም -  load warehouse data",
    "Failed to print receipt": "አልተሳካም -  print receipt",
    "Failed to reject user. Please try again.": "አልተሳካም -  reject user. Please try again.",
    "Failed to restock item": "አልተሳካም -  restock item",
    "Female": "ሴት",
    "Fetching cashier queue...": "Fetching cashier queue...",
    "Filters": "ማጣሪያዎች",
    "First Name": "መጀመሪያ ስም",
    "Forgot Password?": "የይለፍ ቃል ረሱ?",
    "Frequently Searched Medicines": "Frequently Searched Medicines",
    "Frequently used operations": "Frequently used operations",
    "Fri": "አርብ",
    "Friday": "አርብ",
    "From:": "From:",
    "Full Name": "ሙሉ ስም",
    "Full access (all permissions)": "Full access (all permissions)",
    "Full name": "Full name",
    "Gender": "ጾታ",
    "Generating PDF...": "Generating PDF...",
    "Generic": "Generic",
    "Generic Name": "Generic Name",
    "Generic:": "Generic:",
    "Get started by creating your first branch": "Get started by creating your first branch",
    "Great!": "Great!",
    "Guest": "እንግዳ",
    "High": "High",
    "I agree to the Terms & Conditions": "I agree to the Terms & Conditions",
    "ID": "ID",
    "ID:": "ID:",
    "IP Address": "IP Address",
    "Image": "Image",
    "Image size must be less than 2MB": "Image size must be less than 2MB",
    "In Stock": "በክምችት ላይ",
    "Inactive": "ንቁ ያልሆነ",
    "Increase quantity": "Increase quantity",
    "Inspect Items": "እቃዎችን ፈትሽ",
    "Inspect Shelf Medicines": "Inspect Shelf Medicines",
    "Inventory & Warehousing": "ክምችት እና መጋዘን",
    "Inventory Management System": "Inventory Management System",
    "Inventory Report (": "Inventory Report (",
    "Inventory Status": "የክምችት ሁኔታ",
    "Inventory by Category": "ክምችት በምድብ",
    "Inventory is safe for this period": "Inventory is safe for this period",
    "Item": "Item",
    "Item already added": "Item already added",
    "Items": "እቃዎች",
    "Items (": "Items (",
    "Items in Cart": "Items in Cart",
    "Items on Shelf": "Items on Shelf",
    "Items purchased in this sale": "Items purchased in this sale",
    "JPEG, PNG, GIF, WebP (max 2MB)": "JPEG, PNG, GIF, WebP (max 2MB)",
    "JPG, PNG, GIF up to 2MB": "JPG, PNG, GIF up to 2MB",
    "Last Name": "የአባት ስም",
    "Last Updated": "Last Updated",
    "Latest system events": "Latest system events",
    "Let this applicant know why their registration was rejected...": "Let this applicant know why their registration was rejected...",
    "License Document": "License Document",
    "License Expiry Date": "License Expiry Date",
    "License Number": "License Number",
    "Line Items (": "Line Items (",
    "List Table View": "List Table View",
    "Loading Categories & Shelves...": "Loading Categories & Shelves...",
    "Loading audit logs...": "Loading audit logs...",
    "Loading branches...": "Loading branches...",
    "Loading category...": "Loading category...",
    "Loading dashboard...": "Loading dashboard...",
    "Loading inventory data...": "Loading inventory data...",
    "Loading medicines...": "Loading medicines...",
    "Loading products...": "Loading products...",
    "Loading purchase order...": "Loading purchase order...",
    "Loading purchase orders...": "Loading purchase orders...",
    "Loading receipt...": "Loading receipt...",
    "Loading reports...": "Loading reports...",
    "Loading retail products...": "Loading retail products...",
    "Loading roles...": "Loading roles...",
    "Loading sale details...": "Loading sale details...",
    "Loading sales history...": "Loading sales history...",
    "Loading shelf inventory...": "Loading shelf inventory...",
    "Loading shelf items...": "Loading shelf items...",
    "Loading stock data...": "Loading stock data...",
    "Loading supplier...": "Loading supplier...",
    "Loading users...": "Loading users...",
    "Loading warehouse data...": "Loading warehouse data...",
    "Location": "Location",
    "Location *": "Location *",
    "Location Type *": "Location Type *",
    "Locations": "Locations",
    "Logout": "ውጣ",
    "Lost": "Lost",
    "Low": "Low",
    "Low Stock": "ዝቅተኛ ክምችት",
    "Low Stock Alert": "Low Stock Alert",
    "Low Stock Alerts": "የዝቅተኛ ክምችት ማስጠንቀቂያዎች",
    "Low Stock Management": "Low Stock Management",
    "Low Stock Medicines": "ዝቅተኛ ክምችት ያላቸው መድኃኒቶች",
    "Low Stock Report (": "Low Stock Report (",
    "Main": "ዋና",
    "Male": "ወንድ",
    "Manage Your Pharmacy": "Manage Your Pharmacy",
    "Manage central inventory, receiving, and transfers": "Manage central inventory, receiving, and transfers",
    "Manage pharmacy branches and locations": "Manage pharmacy branches and locations",
    "Manage pharmacy staff accounts and permissions": "Manage pharmacy staff accounts and permissions",
    "Manager": "Manager",
    "Manager Name": "Manager Name",
    "Manufacturer": "Manufacturer",
    "Mark as Delivered": "እንደደረሰ ምልክት አድርግ",
    "Medical Device": "Medical Device",
    "Medicine": "መድኃኒት",
    "Medicine *": "Medicine *",
    "Medicine Categories": "የመድኃኒት ምድቦች",
    "Medicine Details": "Medicine Details",
    "Medicine Image": "Medicine Image",
    "Medicine Name": "Medicine Name",
    "Medicine Name *": "Medicine Name *",
    "Medicine created successfully": "Medicine created በተሳካ ሁኔታ",
    "Medicine deleted successfully": "መድኃኒት በተሳካ ሁኔታ ተሰርዟል",
    "Medicine list": "Medicine list",
    "Medicine not found": "Medicine not found",
    "Medicine preview": "Medicine preview",
    "Medicine updated successfully": "መድኃኒት በተሳካ ሁኔታ ተሻሽሏል",
    "Medicines": "መድኃኒቶች",
    "Medicines (": "Medicines (",
    "Medicines approaching expiry date": "Medicines approaching expiry date",
    "Medicines that need restocking": "Medicines that need restocking",
    "Medium": "Medium",
    "Min 8 characters": "Min 8 characters",
    "Module": "Module",
    "Modules Used": "Modules Used",
    "Mon": "ሰኞ",
    "Monday": "ሰኞ",
    "Monitor inventory health with visual metrics": "Monitor inventory health with visual metrics",
    "Monthly": "ወርሃዊ",
    "Movement #": "Movement #",
    "Movement Type *": "Movement Type *",
    "Name": "ስም",
    "Name *": "Name *",
    "Name A-Z": "Name A-Z",
    "Name Z-A": "Name Z-A",
    "Name:": "Name:",
    "National ID": "National ID",
    "New Movement": "New Movement",
    "New Order": "New Order",
    "New Password": "አዲስ የይለፍ ቃል",
    "New Role": "New Role",
    "New Supplier": "New Supplier",
    "New Transfer Request": "New Transfer Request",
    "New activity will appear here.": "New activity will appear here.",
    "Next": "Next",
    "No Branch": "ምንም ቅርንጫፍ የለም",
    "No Expiring Medicines": "No Expiring Medicines",
    "No PDF data available.": "No PDF data available.",
    "No Recent Activity": "No Recent Activity",
    "No audit logs found": "No audit logs found",
    "No branch shelves found": "No branch shelves found",
    "No branches found": "ምንም ቅርንጫፎች አልተገኙም",
    "No categories found": "ምንም ምድቦች አልተገኙም",
    "No data available": "No data available",
    "No items": "No items",
    "No items found": "ምንም እቃዎች አልተገኙም",
    "No items in this sale": "No items in this sale",
    "No medications found": "No medications found",
    "No medicine shelves found for this branch.": "No medicine shelves found for this branch.",
    "No medicines are running low.": "No medicines are running low.",
    "No medicines assigned to this shelf yet": "No medicines assigned to this shelf yet",
    "No medicines found": "ምንም መድኃኒቶች አልተገኙም",
    "No medicines match your current filters.": "No medicines match your current filters.",
    "No medicines on this shelf": "No medicines on this shelf",
    "No permissions assigned yet.": "No permissions assigned yet.",
    "No products added yet. Search and add products above.": "No products added yet. Search and add products above.",
    "No products expiring soon.": "No products expiring soon.",
    "No products found": "No products found",
    "No purchase orders found": "No purchase orders found",
    "No recent actions": "ምንም የቅርብ ጊዜ እርምጃዎች የሉም",
    "No recent sales.": "የቅርብ ጊዜ ሽያጮች የሉም።",
    "No retail products found": "No retail products found",
    "No sales available": "No sales available",
    "No sales found. Try adjusting your search or filters.": "No sales found. Try adjusting your search or filters.",
    "No sales recorded for today yet.": "ዛሬ እስካሁን የተመዘገበ ሽያጭ የለም።",
    "No shelves available": "No shelves available",
    "No shelves found": "ምንም መደርደሪያዎች አልተገኙም",
    "No shelves found. Please create a shelf first.": "No shelves found. Please create a shelf first.",
    "No stock movements found": "No stock movements found",
    "No stock movements recorded": "No stock movements recorded",
    "No suppliers found": "ምንም አቅራቢዎች አልተገኙም",
    "No transfer history yet": "No transfer history yet",
    "No users found": "ምንም ተጠቃሚዎች አልተገኙም",
    "No warehouse shelves found": "No warehouse shelves found",
    "None": "None",
    "Notes": "ማስታወሻዎች",
    "Notes (Optional)": "Notes (Optional)",
    "OTC and retail products": "OTC and retail products",
    "Only admins and pharmacists can create": "Only admins and pharmacists can create",
    "Only admins and pharmacists can delete categories": "Only admins and pharmacists can delete categories",
    "Only admins and pharmacists can delete shelves": "Only admins and pharmacists can delete shelves",
    "Only admins and pharmacists can edit": "Only admins and pharmacists can edit",
    "Opening Point of Sale...": "Opening Point of Sale...",
    "Opening prescription terminal...": "Opening prescription terminal...",
    "Opening retail terminal...": "Opening retail terminal...",
    "Optional classification": "Optional classification",
    "Optional notes": "Optional notes",
    "Order Date": "የትዕዛዝ ቀን",
    "Order Items": "Order Items",
    "Order Items (": "Order Items (",
    "Order Now": "Order Now",
    "Order Ref": "Order Ref",
    "Order dispatched to Cashier queue!": "Order dispatched to Cashier queue!",
    "Order is empty": "ትዕዛዙ ባዶ ነው",
    "Order sent to Checkout!": "Order sent to Checkout!",
    "Order status overview": "Order status overview",
    "Other (specify)": "Other (specify)",
    "Out Of Stock": "ከክምችት ውጭ",
    "Out of Stock": "ከክምችት ውጭ",
    "Out of stock": "Out of stock",
    "Over The Counter (OTC)": "Over The Counter (OTC)",
    "PDF": "PDF",
    "PO Number": "የPO ቁጥር",
    "PO-": "PO-",
    "Page": "Page",
    "Password": "የይለፍ ቃል",
    "Patient Name": "Patient Name",
    "Patient Name is required": "Patient Name is required",
    "Payment Method": "የክፍያ ዘዴ",
    "Payment Status": "Payment Status",
    "Payment Successful": "Payment ስኬትful",
    "Payment completed successfully!": "Payment completed በተሳካ ሁኔታ!",
    "Pending": "በመጠበቅ ላይ",
    "Pending Approval": "Pending Approval",
    "Pending Cashier": "ገንዘብ ተቀባይ በመጠባበቅ ላይ",
    "Pending Requests": "Pending Requests",
    "Permissions": "Permissions",
    "PharmaSys": "PharmaSys",
    "Pharmacist": "ፋርማሲስት",
    "Pharmacists": "Pharmacists",
    "Pharmacy License": "Pharmacy License",
    "Phone": "ስልክ",
    "Phone Number": "Phone Number",
    "Phone Number is required": "Phone Number is required",
    "Phone number": "Phone number",
    "Please add at least one product to the movement.": "Please add at least one product to the movement.",
    "Please add at least one product to the order.": "Please add at least one product to the order.",
    "Please add at least one product.": "Please add at least one product.",
    "Please allow popups to enable printing": "Please allow popups to enable printing",
    "Please complete the Telebirr payment first": "Please complete the Telebirr payment first",
    "Please enter valid quantities for all items.": "Please enter valid quantities for all items.",
    "Please fix the validation errors": "Please fix the validation errors",
    "Please select a destination shelf": "Please select a destination shelf",
    "Please select a movement type.": "Please select a movement type.",
    "Please upload a valid image (JPEG, PNG, GIF, or WebP)": "Please upload a valid image (JPEG, PNG, GIF, or WebP)",
    "Point of Sale": "የሽያጭ ቦታ",
    "Preparing PDF export...": "Preparing PDF export...",
    "Preparing printable receipt...": "Preparing printable receipt...",
    "Prescription & Patient Information": "Prescription & Patient Information",
    "Prescription Checkout": "የማዘዣ ክፍያ",
    "Prescription Draft": "Prescription Draft",
    "Prescription Notes": "Prescription Notes",
    "Prescription Only": "Prescription Only",
    "Prescription Sales": "የማዘዣ ሽያጭ",
    "Prescription medications": "Prescription medications",
    "Preview": "ቅድመ እይታ",
    "Previous": "Previous",
    "Price": "ዋጋ",
    "Print": "Print",
    "Print Receipt": "Print Receipt",
    "Priority": "Priority",
    "Product": "Product",
    "Product Details": "Product Details",
    "Product Image": "Product Image",
    "Product Management": "የምርት አስተዳደር",
    "Product Name": "የምርት ስም",
    "Product Name *": "Product Name *",
    "Product Type *": "Product Type *",
    "Products * (Add one or more)": "Products * (Add one or more)",
    "Professional Registration": "Professional Registration",
    "Profile": "ፕሮፋይል",
    "Profile Photo": "Profile Photo",
    "Progress": "Progress",
    "Purchase Order": "Purchase Order",
    "Purchase Order PDF Preview": "Purchase Order PDF Preview",
    "Purchase Orders": "የግዢ ትዕዛዞች",
    "Purchase Orders (": "Purchase Orders (",
    "Purchase Price": "Purchase Price",
    "Purchase order created successfully": "Purchase order created በተሳካ ሁኔታ",
    "Purchase order deleted": "Purchase order deleted",
    "Purchase order not found.": "Purchase order not found.",
    "Purchase order updated successfully": "Purchase order updated በተሳካ ሁኔታ",
    "Purchased Items (": "Purchased Items (",
    "Purchases": "ግዢዎች",
    "Qty": "Qty",
    "Qty Moved": "Qty Moved",
    "Qty:": "Qty:",
    "Qualification": "Qualification",
    "Qualification Document": "Qualification Document",
    "Quantity": "ብዛት",
    "Quantity *": "ብዛት *",
    "Quantity Received *": "Quantity Received *",
    "Quantity to Add *": "Quantity to Add *",
    "Quantity:": "Quantity:",
    "Quick Actions": "ፈጣን እርምጃዎች",
    "Reason": "Reason",
    "Reason (optional)": "Reason (optional)",
    "Receipt": "ደረሰኝ",
    "Receipt Number": "Receipt Number",
    "Receipt PDF downloaded successfully": "Receipt PDF downloaded በተሳካ ሁኔታ",
    "Receipt not found.": "Receipt not found.",
    "Receive Shipment": "Receive Shipment",
    "Receive Stock": "Receive Stock",
    "Received stock can only be placed on warehouse shelves.": "Received stock can only be placed on warehouse shelves.",
    "Recent Actions": "የቅርብ ጊዜ እርምጃዎች",
    "Recent Activity": "የቅርብ ጊዜ እንቅስቃሴ",
    "Recent Sales": "የቅርብ ጊዜ ሽያጮች",
    "Record": "Record",
    "Record ID": "Record ID",
    "Record Movement (": "Record Movement (",
    "Record Movements": "Record Movements",
    "Record Stock Movement": "Record Stock Movement",
    "Record your first movement": "Record your first movement",
    "Reference": "Reference",
    "Refresh": "Refresh",
    "Refresh Queue": "Refresh Queue",
    "Register": "ተመዝገብ",
    "Register as a pharmacist or cashier": "Register as a pharmacist or cashier",
    "Register here": "እዚህ ይመዝገቡ",
    "Registration number": "Registration number",
    "Reject": "ውድቅ አድርግ",
    "Rejected": "ውድቅ የተደረገ",
    "Remaining": "ቀሪ",
    "Remember Me": "አስታውሰኝ",
    "Remove": "አስወግድ",
    "Remove from history": "Remove from history",
    "Remove item": "Remove item",
    "Removed from search history": "Removed from search history",
    "Reorder": "Reorder",
    "Reorder Level": "Reorder Level",
    "Reorder Level *": "የድጋሚ ማዘዣ መጠን *",
    "Reorder:": "Reorder:",
    "Reports": "ሪፖርቶች",
    "Reports & Analytics": "ሪፖርቶች እና ትንታኔዎች",
    "Request new code": "Request new code",
    "Request stock to be transferred to a branch. Track approval and delivery from the Transfer History tab.": "Request stock to be transferred to a branch. Track approval and delivery from the Transfer History tab.",
    "Resend to Supplier": "Resend to Supplier",
    "Reset Code": "Reset Code",
    "Reset Your Password": "Reset Your Password",
    "Restock": "Restock",
    "Restock Product": "Restock Product",
    "Retail & OTC": "ችርቻሮ እና የሐኪም ማዘዣ የሌላቸው (OTC)",
    "Retail & OTC (": "Retail & OTC (",
    "Retail & OTC Products": "የችርቻሮ እና የሐኪም ማዘዣ የሌላቸው ምርቶች",
    "Retail & OTC Sales": "የችርቻሮ እና የሐኪም ማዘዣ የሌላቸው ሽያጮች",
    "Retail / OTC Products": "Retail / OTC Products",
    "Retail Draft": "Retail Draft",
    "Retail Point of Sale": "የችርቻሮ ሽያጭ ቦታ",
    "Retail Product Details": "Retail Product Details",
    "Retail product created successfully": "Retail product created በተሳካ ሁኔታ",
    "Retail product deleted successfully": "Retail product deleted በተሳካ ሁኔታ",
    "Retail product updated successfully": "Retail product updated በተሳካ ሁኔታ",
    "Retry": "Retry",
    "Returns": "Returns",
    "Revenue (Last 7 Days)": "ገቢ (ያለፉት 7 ቀናት)",
    "Review Summary": "Review Summary",
    "Role": "ሚና",
    "Role Name": "Role Name",
    "Role can only be changed by an administrator.": "Role can only be changed by an administrator.",
    "Role created successfully": "Role created በተሳካ ሁኔታ",
    "Role deleted successfully": "Role deleted በተሳካ ሁኔታ",
    "Role name is required": "Role name is required",
    "Role updated successfully": "Role updated በተሳካ ሁኔታ",
    "Roles & Permissions": "ሚናዎች እና ፈቃዶች",
    "SKU": "SKU",
    "SKU:": "SKU:",
    "Sale": "Sale",
    "Sales": "ሽያጭ",
    "Sales (Last 7 Days)": "ሽያጭ (ያለፉት 7 ቀናት)",
    "Sales Analytics": "Sales Analytics",
    "Sales Checkout": "የሽያጭ ክፍያ",
    "Sales History": "የሽያጭ ታሪክ",
    "Sales Report (": "Sales Report (",
    "Sat": "ቅዳሜ",
    "Saturday": "ቅዳሜ",
    "Scan or type barcode": "Scan or type barcode",
    "Search and select products": "Search and select products",
    "Search audit logs...": "Search audit logs...",
    "Search branches...": "Search branches...",
    "Search by medicine name or generic name...": "Search by medicine name or generic name...",
    "Search by medicine name, generic name, or batch...": "Search by medicine name, generic name, or batch...",
    "Search by name or email...": "Search by name or email...",
    "Search by name, generic name, SKU, or barcode...": "Search by name, generic name, SKU, or barcode...",
    "Search by product name, SKU, or barcode...": "Search by product name, SKU, or barcode...",
    "Search by receipt number or customer...": "Search by receipt number or customer...",
    "Search history cleared": "Search history cleared",
    "Search items by name, barcode...": "Search items by name, barcode...",
    "Search medication...": "Search medication...",
    "Search medicine, generic, barcode...": "Search medicine, generic, barcode...",
    "Search medicines by name, generic, or barcode...": "Search medicines by name, generic, or barcode...",
    "Search medicines by name...": "Search medicines by name...",
    "Search medicines or retail & OTC products...": "Search medicines or retail & OTC products...",
    "Search movements...": "Search movements...",
    "Search products...": "ምርቶችን ፈልግ...",
    "Search retail & OTC products...": "Search retail & OTC products...",
    "Search retail products by name, SKU, or barcode...": "Search retail products by name, SKU, or barcode...",
    "Search suppliers...": "Search suppliers...",
    "Select Branch": "ቅርንጫፍ ይምረጡ",
    "Select Branch Medicine Shelf": "Select Branch Medicine Shelf",
    "Select Category": "ምድብ ይምረጡ",
    "Select Destination Branch": "Select Destination Branch",
    "Select Dosage Form": "Select Dosage Form",
    "Select Medicine": "Select Medicine",
    "Select Payment Method": "Select Payment Method",
    "Select Purchase Order": "Select Purchase Order",
    "Select Self Category": "Select Self Category",
    "Select Shelf": "መደርደሪያ ይምረጡ",
    "Select Source Branch": "Select Source Branch",
    "Select Supplier": "Select Supplier",
    "Select Unit": "Select Unit",
    "Select Warehouse Shelf": "Select Warehouse Shelf",
    "Select an item from the list": "Select an item from the list",
    "Select gender": "Select gender",
    "Selected Items (": "Selected Items (",
    "Self": "Self",
    "Self Category": "Self Category",
    "Selling Price": "የመሸጫ ዋጋ",
    "Selling Price *": "የመሸጫ ዋጋ *",
    "Selling Price:": "Selling Price:",
    "Send to Checkout": "Send to Checkout",
    "Send to Supplier": "Send to Supplier",
    "Sending Code...": "Sending Code...",
    "Sent At": "Sent At",
    "Settings": "ቅንብሮች",
    "Shelf": "Shelf",
    "Shelf Code *": "Shelf Code *",
    "Shelf Location": "የመደርደሪያ ቦታ",
    "Shelf Name *": "Shelf Name *",
    "Shelf deleted successfully": "መደርደሪያ በተሳካ ሁኔታ ተሰርዟል",
    "Shelves": "መደርደሪያዎች",
    "Showing": "Showing",
    "Showing 20 of": "Showing 20 of",
    "Showing 5 of": "Showing 5 of",
    "Showing first 50 of": "Showing first 50 of",
    "Showing medicines, retail products, stock levels, alerts, and sales analytics exclusively for this location.": "መድኃኒቶችን፣ የችርቻሮ ምርቶችን፣ የክምችት ደረጃዎችን፣ ማስጠንቀቂያዎችን እና የሽያጭ ትንተናዎችን ለዚህ ቦታ ብቻ ያሳያል።",
    "Sign In": "ግባ",
    "Sign in": "Sign in",
    "Sign in to your account": "ወደ አካውንትዎ ይግቡ",
    "Signing In...": "Signing In...",
    "Smart Pharmacy Inventory System": "Smart Pharmacy Inventory System",
    "Something went wrong": "Something went wrong",
    "Source": "Source",
    "Source Branch *": "Source Branch *",
    "Source Type": "Source Type",
    "Status": "ሁኔታ",
    "Status:": "Status:",
    "Stock": "ክምችት",
    "Stock High-Low": "Stock High-Low",
    "Stock In": "Stock In",
    "Stock Inventory": "የክምችት አስተዳደር",
    "Stock Low-High": "Stock Low-High",
    "Stock Management": "የክምችት አስተዳደር",
    "Stock Movements": "የክምችት እንቅስቃሴዎች",
    "Stock Out": "Stock Out",
    "Stock Status": "Stock Status",
    "Stock Value": "Stock Value",
    "Stock health overview": "Stock health overview",
    "Stock movement deleted": "Stock movement deleted",
    "Stock movements recorded successfully": "Stock movements recorded በተሳካ ሁኔታ",
    "Stock received successfully": "Stock received በተሳካ ሁኔታ",
    "Stock:": "Stock:",
    "Strength": "Strength",
    "Submit to Pending": "Submit to Pending",
    "Subtotal": "Subtotal",
    "Sun": "እሑድ",
    "Sunday": "እሑድ",
    "Supplier": "አቅራቢ",
    "Supplier Details": "Supplier Details",
    "Supplier created successfully": "አቅራቢ በተሳካ ሁኔታ ተፈጥሯል",
    "Supplier deleted successfully": "አቅራቢ በተሳካ ሁኔታ ተሰርዟል",
    "Supplier not found.": "Supplier not found.",
    "Supplier updated successfully": "አቅራቢ በተሳካ ሁኔታ ተሻሽሏል",
    "Suppliers": "አቅራቢዎች",
    "Suppliers Directory": "የአቅራቢዎች ማውጫ",
    "Switch Branch": "ቅርንጫፍ ቀይር",
    "Switch Branch View": "የቅርንጫፍ እይታ ቀይር",
    "System": "ስርዓት",
    "System Reports": "የስርዓት ሪፖርቶች",
    "Table": "ሰንጠረዥ",
    "Thank you for shopping with us.": "ስለገዙልን እናመሰግናለን።",
    "The sale has been completed successfully.": "The sale has been completed በተሳካ ሁኔታ.",
    "This is a": "This is a",
    "Thu": "ሐሙስ",
    "Thursday": "ሐሙስ",
    "To Branch *": "To Branch *",
    "To:": "To:",
    "Today": "ዛሬ",
    "Today's Actions": "Today's Actions",
    "Today's Revenue": "የዛሬ ገቢ",
    "Today's Sales": "የዛሬ ሽያጮች",
    "Today's Sales by Hour": "በሰዓት የዛሬ ሽያጮች",
    "Total": "አጠቃላይ",
    "Total Amount": "አጠቃላይ መጠን",
    "Total Amount:": "አጠቃላይ መጠን:",
    "Total Branches": "አጠቃላይ ቅርንጫፎች",
    "Total Items": "አጠቃላይ እቃዎች",
    "Total Items:": "አጠቃላይ እቃዎች:",
    "Total Medicines": "አጠቃላይ መድኃኒቶች",
    "Total Price:": "አጠቃላይ ዋጋ:",
    "Total Records": "አጠቃላይ መዝገቦች",
    "Total Sales": "አጠቃላይ ሽያጮች",
    "Total Shelves": "አጠቃላይ መደርደሪያዎች",
    "Total Stock": "አጠቃላይ ክምችት",
    "Total Stock Units": "አጠቃላይ የክምችት ክፍሎች",
    "Total Users": "አጠቃላይ ተጠቃሚዎች",
    "Total inventory value": "አጠቃላይ የክምችት ዋጋ",
    "Track and manage inventory movements": "የክምችት እንቅስቃሴዎችን ይከተሉ እና ያስተዳድሩ",
    "Transfer approved successfully": "Transfer approved በተሳካ ሁኔታ",
    "Transfer completed successfully": "Transfer completed በተሳካ ሁኔታ",
    "Transfer request created successfully": "Transfer request created በተሳካ ሁኔታ",
    "Transfer to": "ወደ ... አስተላልፍ",
    "Transfers": "ዝውውሮች",
    "Try adjusting your search terms": "የፍለጋ ቃላትን ለማስተካከል ይሞክሩ",
    "Tue": "ማክሰኞ",
    "Tuesday": "ማክሰኞ",
    "Type": "አይነት",
    "Type custom dosage form": "ብጁ የመድኃኒት መጠን ቅጽ ያስገቡ",
    "Type custom unit": "ብጁ ክፍል ያስገቡ",
    "Unable to load category details.": "የምድብ ዝርዝሮችን መጫን አልተቻለም።",
    "Unable to load purchase order details.": "የግዢ ትዕዛዝ ዝርዝሮችን መጫን አልተቻለም።",
    "Unable to load supplier details.": "የአቅራቢ ዝርዝሮችን መጫን አልተቻለም።",
    "Unauthorized access": "ያልተፈቀደ መዳረሻ",
    "Unit": "ክፍል",
    "Unit Price": "የአሃድ ዋጋ",
    "University": "ዩኒቨርሲቲ",
    "University name": "የዩኒቨርሲቲ ስም",
    "Update Category": "ምድብ አሻሽል",
    "Update Order": "ትዕዛዝ አሻሽል",
    "Update Supplier": "አቅራቢ አሻሽል",
    "Upload": "ስቀል",
    "Upload License": "ፈቃድ ስቀል",
    "Upload Qualification": "ብቃት ስቀል",
    "Urgent": "አስቸኳይ",
    "User": "ተጠቃሚ",
    "User Management": "የተጠቃሚ አስተዳደር",
    "User Profile": "የተጠቃሚ መገለጫ",
    "User approved successfully.": "User approved በተሳካ ሁኔታ.",
    "User registration rejected.": "የተጠቃሚ ምዝገባ ውድቅ ተደርጓል።",
    "Users": "ተጠቃሚዎች",
    "Utilization": "አጠቃቀም",
    "Verification code sent to": "የማረጋገጫ ኮድ ወደ ... ተልኳል",
    "View": "አሳይ",
    "View All": "ሁሉንም ይመልከቱ",
    "View Details": "ዝርዝሮችን ይመልከቱ",
    "View Items (": "እቃዎችን ይመልከቱ (",
    "View Receipt": "ደረሰኝ ይመልከቱ",
    "View Sale Details": "የሽያጭ ዝርዝሮችን ይመልከቱ",
    "View and manage inventory across medicines and retail / OTC products": "View and manage inventory across medicines and retail / OTC products",
    "View only": "ለማየት ብቻ",
    "Warehouse": "መጋዘን",
    "Warehouse Shelf *": "የመጋዘን መደርደሪያ *",
    "Wed": "ረቡዕ",
    "Wednesday": "ረቡዕ",
    "Weekly": "ሳምንታዊ",
    "Welcome Back": "እንኳን ደህና መጡ",
    "What is this role responsible for?": "ይህ ሚና ለምን ኃላፊነት አለበት?",
    "Years of Experience": "የልምድ ዓமታት",
    "You do not have permission to add medicines": "መድኃኒቶችን ለመጨመር ፈቃድ የለዎትም",
    "You do not have permission to create categories": "ምድቦችን ለመፍጠር ፈቃድ የለዎትም",
    "You do not have permission to delete categories": "ምድቦችን ለመሰረዝ ፈቃድ የለዎትም",
    "You do not have permission to delete medicines": "መድኃኒቶችን ለመሰረዝ ፈቃድ የለዎትም",
    "You do not have permission to delete suppliers": "አቅራቢዎችን ለመሰረዝ ፈቃድ የለዎትም",
    "You do not have permission to edit categories": "ምድቦችን ለማስተካከል ፈቃድ የለዎትም",
    "You do not have permission to edit medicines": "መድኃኒቶችን ለማስተካከል ፈቃድ የለዎትም",
    "You do not have permission to perform this action": "ይህንን እርምጃ ለመፈጸም ፈቃድ የለዎትም",
    "admin": "አስተዳዳሪ",
    "cashier": "ገንዘብ ተቀባይ",
    "days left)": "ቀናት ቀሩ)",
    "e.g. +251-911-123456": "e.g. +251-911-123456",
    "e.g. 500mg, 10%": "e.g. 500mg, 10%",
    "e.g. A-2-3": "e.g. A-2-3",
    "e.g. Acetaminophen": "e.g. Acetaminophen",
    "e.g. Addis Ababa, Bole Road": "e.g. Addis Ababa, Bole Road",
    "e.g. BATCH-001": "e.g. BATCH-001",
    "e.g. COS-001": "e.g. COS-001",
    "e.g. Downtown Pharmacy": "e.g. Downtown Pharmacy",
    "e.g. GSK": "e.g. GSK",
    "e.g. GSK, Pfizer": "e.g. GSK, Pfizer",
    "e.g. Inventory Manager": "e.g. Inventory Manager",
    "e.g. John Smith": "e.g. John Smith",
    "e.g. Lipstick - Ruby Red": "e.g. Lipstick - Ruby Red",
    "e.g. MSA-01": "e.g. MSA-01",
    "e.g. Medicine Shelf A": "e.g. Medicine Shelf A",
    "e.g. Paracetamol": "e.g. Paracetamol",
    "e.g. Paracetamol Extra": "e.g. Paracetamol Extra",
    "e.g. Pharmacy, B.Pharm": "e.g. Pharmacy, B.Pharm",
    "e.g. branch@pharmacy.com": "e.g. branch@pharmacy.com",
    "e.g., GSK, Pfizer": "e.g., GSK, Pfizer",
    "e.g., New shipment from supplier": "e.g., New shipment from supplier",
    "example@email.com": "example@email.com",
    "expiring medicines": "የሚያበቁ መድኃኒቶች",
    "in order": "በትዕዛዝ",
    "item(s)": "እቃ(ዎች)",
    "item(s) (": "እቃ(ዎች) (",
    "items • Refine search to see more": "እቃዎች • ፍለጋውን ያጥቡ",
    "items)": "እቃዎች)",
    "more —": "ተጨማሪ —",
    "permissions available": "የሚገኙ ፈቃዶች",
    "permissions granted.": "የተሰጡ ፈቃዶች።",
    "pharmacist": "ፋርማሲስት",
    "products ·": "ምርቶች ·",
    "results. Refine search to see more.": "ውጤቶች። ፍለጋውን ያጥቡ።",
    "sales)": "ሽያጮች)",
    "shelf belonging to that branch. Capacity is enforced.": "shelf belonging to that branch. Capacity is enforced.",
    "shelf. It is not assigned to any branch and can only hold received warehouse stock.": "shelf. It is not assigned to any branch and can only hold received warehouse stock.",
    "spaces left": "ባዶ ቦታዎች ቀሩ",
    "units)": "ክፍሎች)",
    "warehouse & pharmacy shelf locations": "warehouse & pharmacy shelf locations",
    "with Confidence": "with Confidence",
    "x)": "x)",
    "you@example.com": "you@example.com",
    "| Qty:": "| Qty:",
    "• Page": "• Page",
    "✓ No expired medicines": "✓ ጊዜያቸው ያለፈባቸው መድኃኒቶች የሉም",
    "✓ No low-stock medicines": "✓ ዝቅተኛ ክምችት ያላቸው መድኃኒቶች የሉም",
    "✓ Payment Successful": "✓ ክፍያው በተሳካ ሁኔታ ተጠናቋል"
  }
};
function getInitialLanguage() {
  const stored = localStorage.getItem(LANGUAGE_KEY);
  if (stored === 'en' || stored === 'am') {
    return stored;
  }
  return 'en';
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem(LANGUAGE_KEY, lang);
  }, [lang]);

  const toggleLanguage = () => {
    setLang((prev) => prev === 'en' ? 'am' : 'en');
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>);

}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};